// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpKHXP1BhbBSknviyfrPGuAZSzHy2exaw',
    appId: '1:578248215486:web:8d7a0cd398e36236a007ef',
    messagingSenderId: '578248215486',
    projectId: 'islam-insta',
    authDomain: 'islam-insta.firebaseapp.com',
    storageBucket: 'islam-insta.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-8W0KX77eeMaRbnE8UB5DYuhgPdjEFb8',
    appId: '1:578248215486:android:23d3ce852472cf7aa007ef',
    messagingSenderId: '578248215486',
    projectId: 'islam-insta',
    storageBucket: 'islam-insta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN7pCzDrsNkaWxsQvocJyApjcLFimtgfQ',
    appId: '1:578248215486:ios:ef37bf4afa392705a007ef',
    messagingSenderId: '578248215486',
    projectId: 'islam-insta',
    storageBucket: 'islam-insta.appspot.com',
    iosBundleId: 'com.example.islamInstegram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN7pCzDrsNkaWxsQvocJyApjcLFimtgfQ',
    appId: '1:578248215486:ios:ef37bf4afa392705a007ef',
    messagingSenderId: '578248215486',
    projectId: 'islam-insta',
    storageBucket: 'islam-insta.appspot.com',
    iosBundleId: 'com.example.islamInstegram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpKHXP1BhbBSknviyfrPGuAZSzHy2exaw',
    appId: '1:578248215486:web:4684423ad98d4a25a007ef',
    messagingSenderId: '578248215486',
    projectId: 'islam-insta',
    authDomain: 'islam-insta.firebaseapp.com',
    storageBucket: 'islam-insta.appspot.com',
  );

}